-- CreateTable
CREATE TABLE "Property" (
    "id" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "emi" DOUBLE PRECISION,
    "homeLoanEligible" BOOLEAN NOT NULL DEFAULT false,
    "area" INTEGER NOT NULL,
    "bhk" INTEGER NOT NULL,
    "propertyType" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "images" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "beds" INTEGER NOT NULL,
    "baths" INTEGER NOT NULL,
    "balconies" INTEGER NOT NULL,
    "furnishingStatus" TEXT NOT NULL,
    "carpetArea" INTEGER NOT NULL,
    "pricePerSqft" DOUBLE PRECISION NOT NULL,
    "floor" INTEGER NOT NULL,
    "totalFloors" INTEGER NOT NULL,
    "transactionType" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "facing" TEXT NOT NULL,
    "ownershipType" TEXT NOT NULL,
    "ageOfConstruction" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "offer" TEXT,
    "overlooking" TEXT,
    "description" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Property_pkey" PRIMARY KEY ("id")
);
